# Generated by Django 4.2.1 on 2023-07-06 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tournament", "0002_ground_tournament_city_alter_tournament_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TournamentGroups",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("status", models.PositiveSmallIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tournament_id",
                    models.ForeignKey(
                        db_column="tournament_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tournamentGroups_tournament",
                        to="tournament.tournament",
                    ),
                ),
            ],
        ),
    ]
