# Generated by Django 4.2.1 on 2023-07-07 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("team", "0009_alter_city_status_alter_team_status"),
        ("group", "0002_alter_tournamentgroups_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TournamentGroupTeams",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("status", models.PositiveSmallIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group_id",
                    models.ForeignKey(
                        db_column="group_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tournamentGroupTeams_tournamentGroups",
                        to="group.tournamentgroups",
                    ),
                ),
                (
                    "team_id",
                    models.ForeignKey(
                        db_column="team_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tournamentGroupTeams_Team",
                        to="team.team",
                    ),
                ),
            ],
            options={
                "db_table": "tournament_group_teams",
            },
        ),
    ]
