# Generated by Django 4.2.1 on 2023-06-15 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("team", "0009_alter_city_status_alter_team_status"),
        ("tournament", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamTournaments",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("status", models.PositiveSmallIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "team_id",
                    models.ForeignKey(
                        db_column="team_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="TeamTournament_team",
                        to="team.team",
                    ),
                ),
                (
                    "tournament_id",
                    models.ForeignKey(
                        db_column="tournament_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="TeamTournament_tournament",
                        to="tournament.tournament",
                    ),
                ),
            ],
            options={
                "db_table": "tournament_teams",
                "unique_together": {("tournament_id", "team_id")},
            },
        ),
    ]
