# Generated by Django 4.2.1 on 2023-05-17 06:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("team", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="logo_url",
            field=models.FileField(blank=True, default=None, null=True, upload_to=""),
        ),
    ]
