# Generated by Django 4.2.1 on 2023-05-18 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("team", "0004_city"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="city",
            field=models.ForeignKey(
                default="1", on_delete=django.db.models.deletion.CASCADE, to="team.city"
            ),
            preserve_default=False,
        ),
    ]
