# Generated by Django 4.2.1 on 2023-06-01 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("team", "0008_alter_city_status_alter_team_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="status",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="team",
            name="status",
            field=models.SmallIntegerField(default=0),
        ),
    ]
