# Generated by Django 4.2.1 on 2023-08-11 07:24

import django.db.models.deletion
from django.db import migrations, models

team = "team.team"


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tournament", "0004_alter_tournament_description"),
        ("team", "0009_alter_city_status_alter_team_status"),
        ("round", "0003_alter_tournamentrounds_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="Matches",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("datetime", models.DateTimeField()),
                ("match_type", models.SmallIntegerField()),
                ("over_per_bowler", models.IntegerField()),
                ("total_overs", models.IntegerField()),
                ("ball_type", models.IntegerField()),
                ("status", models.PositiveSmallIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "city_id",
                    models.ForeignKey(
                        db_column="city_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_city",
                        to="team.city",
                    ),
                ),
                (
                    "ground_id",
                    models.ForeignKey(
                        db_column="ground_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_ground",
                        to="tournament.ground",
                    ),
                ),
                (
                    "round_id",
                    models.ForeignKey(
                        db_column="round_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_round",
                        to="round.round",
                    ),
                ),
                (
                    "team1",
                    models.ForeignKey(
                        db_column="team1",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_team1",
                        to=team,
                    ),
                ),
                (
                    "team2",
                    models.ForeignKey(
                        db_column="team2",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_team2",
                        to=team,
                    ),
                ),
                (
                    "tournament_id",
                    models.ForeignKey(
                        db_column="tournament_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tournament_matches",
                        to="tournament.tournament",
                    ),
                ),
                (
                    "winner_team_id",
                    models.ForeignKey(
                        db_column="winner_team_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_winner",
                        to=team,
                    ),
                ),
            ],
            options={
                "db_table": "matches",
            },
        ),
    ]
