# Generated by Django 4.2.1 on 2023-08-17 12:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("score", "0002_score_created_at_score_status_score_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="score",
            name="runs",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
