# Generated by Django 4.2.1 on 2023-08-21 04:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("score", "0003_score_runs"),
    ]

    operations = [
        migrations.AddField(
            model_name="score",
            name="ball_number",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="score",
            name="over",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
