# Generated by Django 4.2.1 on 2023-06-15 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournament", "0001_initial"),
        ("team", "0009_alter_city_status_alter_team_status"),
        ("team_tournaments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teamtournaments",
            name="team_id",
            field=models.ForeignKey(
                db_column="team_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teamTournament_team",
                to="team.team",
            ),
        ),
        migrations.AlterField(
            model_name="teamtournaments",
            name="tournament_id",
            field=models.ForeignKey(
                db_column="tournament_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teamTournament_tournament",
                to="tournament.tournament",
            ),
        ),
    ]
