# Generated by Django 4.2.1 on 2023-07-25 11:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("round", "0002_tournamentrounds"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="tournamentrounds",
            table="tournament_rounds",
        ),
    ]
