# Generated by Django 4.2.1 on 2023-05-23 11:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

type_1 = "Type 1"
type_2 = "Type 2"
type_3 = "Type 3"


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tournament",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                (
                    "ball_type",
                    models.SmallIntegerField(
                        choices=[(0, type_1), (1, type_2), (2, type_3)]
                    ),
                ),
                (
                    "tournament_type",
                    models.SmallIntegerField(
                        choices=[(0, type_1), (1, type_2), (2, type_3)]
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "match_type",
                    models.SmallIntegerField(
                        choices=[(0, type_1), (1, type_2), (2, type_3)]
                    ),
                ),
                ("description", models.CharField(max_length=255, null=True)),
                (
                    "logo_url",
                    models.FileField(
                        blank=True, default=None, null=True, upload_to="Tour_logo"
                    ),
                ),
                (
                    "banner_url",
                    models.FileField(
                        blank=True, default=None, null=True, upload_to="Tour_banner"
                    ),
                ),
                ("status", models.IntegerField(default=0)),
                ("deleted_reason", models.CharField(max_length=150, null=True)),
                ("deleted_description", models.CharField(max_length=255, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "best_batsman",
                    models.ForeignKey(
                        db_column="best_batsman",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="best_batsman_tournaments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "best_bowler",
                    models.ForeignKey(
                        db_column="best_bowler",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="best_bowler_tournaments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "player_of_tournament",
                    models.ForeignKey(
                        db_column="player_of_tournament",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="best_player_tournaments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tournament",
            },
        ),
    ]
