# Generated by Django 4.2.1 on 2023-08-14 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("team", "0009_alter_city_status_alter_team_status"),
        ("match", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="matches",
            old_name="datetime",
            new_name="date_time",
        ),
        migrations.AlterField(
            model_name="matches",
            name="winner_team_id",
            field=models.ForeignKey(
                db_column="winner_team_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="match_winner",
                to="team.team",
            ),
        ),
    ]
