# Generated by Django 4.2.1 on 2023-07-25 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournament", "0004_alter_tournament_description"),
        ("round", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TournamentRounds",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("status", models.SmallIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "round_id",
                    models.ForeignKey(
                        db_column="round_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tournamentRounds_round",
                        to="round.round",
                    ),
                ),
                (
                    "tournament_id",
                    models.ForeignKey(
                        db_column="tournament_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tournamentRounds_tournament",
                        to="tournament.tournament",
                    ),
                ),
            ],
        ),
    ]
