# Generated by Django 4.2.1 on 2023-07-11 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("round", "0001_initial"),
        ("group", "0003_tournamentgroupteams"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournamentgroups",
            name="round_id",
            field=models.ForeignKey(
                db_column="round_id",
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tournamentGroups_round",
                to="round.round",
            ),
        ),
    ]
