# Generated by Django 4.2.1 on 2023-07-11 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("team", "0009_alter_city_status_alter_team_status"),
        ("tournament", "0002_ground_tournament_city_alter_tournament_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="team.city"
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="ground",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tournament.ground"
            ),
        ),
    ]
