# Generated by Django 4.2.1 on 2023-07-19 03:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournament", "0003_alter_tournament_city_alter_tournament_ground"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="description",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
