# Generated by Django 4.2.1 on 2023-05-17 06:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("team", "0002_alter_team_logo_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="logo_url",
            field=models.FileField(
                blank=True, default=None, null=True, upload_to="my_pictures"
            ),
        ),
    ]
