# Generated by Django 4.2.1 on 2023-05-31 07:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("team", "0006_rename_createdat_team_created_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="city",
            old_name="createdAt",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="city",
            old_name="updatedAt",
            new_name="updated_at",
        ),
    ]
