# Generated by Django 4.2.1 on 2023-06-01 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("team", "0006_rename_createdat_team_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamPlayers",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("status", models.PositiveSmallIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "player_id",
                    models.ForeignKey(
                        db_column="player_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team_id",
                    models.ForeignKey(
                        db_column="team_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="team.team",
                    ),
                ),
            ],
            options={
                "db_table": "team_players",
                "unique_together": {("team_id", "player_id")},
            },
        ),
    ]
